version: '3'
services:
  db:
    image: mysql:5.7
    container_name: ps_db
    ports:
      - "3306:3306"
    volumes:
      - $PWD/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ps
      MYSQL_USER: ps
      MYSQL_PASSWORD: ps
    networks:
      - ps_net
  ps:
    image: prestashop/prestashop
    container_name: ps_web
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - $PWD/html:/var/www/html
    environment:
      DB_SERVER: db
      DB_USER: ps
      DB_PASSWD: ps
      DB_NAME: ps
    networks:
      - ps_net
networks:
  ps_net: