version: '3'
services:
  db:
    container_name: wp_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - $PWD/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - my_net
  wp:
    container_name: wp-web
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"    
    volumes:
      - $PWD/html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: wp_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - my_net
networks:
  my_net: